/**
 * @file j1939_dbc_generated.c
 * @brief Auto-generated J1939 decoder implementations from DBC file
 * 
 * DO NOT EDIT - Generated by dbc_parser.py
 */

#include "j1939_dbc_generated.h"

void decode_request(const uint8_t* data, request_t* out) {
    if (data == NULL || out == NULL) return;

    out->pgn_requested = /* TODO: complex bit extraction for PGNRequested */;
}

void decode_etc1(const uint8_t* data, etc1_t* out) {
    if (data == NULL || out == NULL) return;

    out->input_shaft_speed = (((uint16_t)data[0] | ((uint16_t)data[1] << 8))) * 0.125f + (0.0f);
    out->output_shaft_speed = (((uint16_t)data[2] | ((uint16_t)data[3] << 8))) * 0.125f + (0.0f);
    out->percent_clutch_slip = (data[4]) * 0.4f + (0.0f);
    out->prog_shift_disable = ((data[5] >> 2) & 0x03);
    out->eng_momentary_overspeed_enable = ((data[5] >> 4) & 0x03);
    out->eng_derating_enable = ((data[5] >> 6) & 0x03);
    out->source_address_of_torque_limiting = data[6];
}

void decode_eec2(const uint8_t* data, eec2_t* out) {
    if (data == NULL || out == NULL) return;

    out->accel_pedal_pos1 = (data[1]) * 0.4f + (0.0f);
    out->accel_pedal_pos2 = (data[7]) * 0.4f + (0.0f);
    out->eng_percent_load_at_current_speed = data[2];
    out->remote_accel_pedal_position = (data[3]) * 0.4f + (0.0f);
    out->actual_max_available_engine_percent_torque = (data[5]) * 0.4f + (0.0f);
}

void decode_eec1(const uint8_t* data, eec1_t* out) {
    if (data == NULL || out == NULL) return;

    out->eng_torque_mode = ((data[0] >> 0) & 0x0F);
    out->actual_eng_percent_torque = (data[2]) * 1.0f + (-125.0f);
    out->drivers_demand_eng_percent_torque = (data[1]) * 1.0f + (-125.0f);
    out->engine_speed = (((uint16_t)data[3] | ((uint16_t)data[4] << 8))) * 0.125f + (0.0f);
    out->source_address_of_controlling_device = data[5];
    out->eng_starter_mode = ((data[6] >> 0) & 0x0F);
}

void decode_etc2(const uint8_t* data, etc2_t* out) {
    if (data == NULL || out == NULL) return;

    out->selected_gear = (data[0]) * 1.0f + (-125.0f);
    out->actual_gear_ratio = (((uint16_t)data[1] | ((uint16_t)data[2] << 8))) * 0.001f + (0.0f);
    out->current_gear = (data[3]) * 1.0f + (-125.0f);
    out->trans_requested_range = ((uint16_t)data[4] | ((uint16_t)data[5] << 8));
    out->trans_current_range = ((uint16_t)data[6] | ((uint16_t)data[7] << 8));
}

void decode_vd(const uint8_t* data, vd_t* out) {
    if (data == NULL || out == NULL) return;

    out->total_vehicle_distance = (((uint32_t)data[0] | ((uint32_t)data[1] << 8) | ((uint32_t)data[2] << 16) | ((uint32_t)data[3] << 24))) * 0.125f + (0.0f);
    out->trip_distance = (((uint32_t)data[4] | ((uint32_t)data[5] << 8) | ((uint32_t)data[6] << 16) | ((uint32_t)data[7] << 24))) * 0.125f + (0.0f);
}

void decode_dm1(const uint8_t* data, dm1_t* out) {
    if (data == NULL || out == NULL) return;

    out->protect_lamp = ((data[0] >> 0) & 0x03);
    out->amber_warning_lamp = ((data[0] >> 2) & 0x03);
    out->red_stop_lamp = ((data[0] >> 4) & 0x03);
    out->malfunction_indicator_lamp = ((data[0] >> 6) & 0x03);
    out->flash_protect_lamp = ((data[1] >> 0) & 0x03);
    out->flash_amber_warning_lamp = ((data[1] >> 2) & 0x03);
    out->flash_red_stop_lamp = ((data[1] >> 4) & 0x03);
    out->flash_malfunction_indicator_lamp = ((data[1] >> 6) & 0x03);
    out->spn = /* TODO: complex bit extraction for SPN */;
    out->fmi = ((data[4] >> 3) & 0x1F);
    out->cm = ((data[5] >> 0) & 0x01);
    out->occurrence_count = ((data[5] >> 1) & 0x7F);
}

void decode_hours(const uint8_t* data, hours_t* out) {
    if (data == NULL || out == NULL) return;

    out->eng_total_hours_of_operation = (((uint32_t)data[0] | ((uint32_t)data[1] << 8) | ((uint32_t)data[2] << 16) | ((uint32_t)data[3] << 24))) * 0.05f + (0.0f);
    out->eng_total_revolutions = (((uint32_t)data[4] | ((uint32_t)data[5] << 8) | ((uint32_t)data[6] << 16) | ((uint32_t)data[7] << 24))) * 1000.0f + (0.0f);
}

void decode_et1(const uint8_t* data, et1_t* out) {
    if (data == NULL || out == NULL) return;

    out->engine_coolant_temperature = (data[0]) * 1.0f + (-40.0f);
    out->fuel_temperature1 = (data[1]) * 1.0f + (-40.0f);
    out->engine_oil_temperature1 = (((uint16_t)data[2] | ((uint16_t)data[3] << 8))) * 0.03125f + (-273.0f);
    out->turbo_oil_temperature = (((uint16_t)data[4] | ((uint16_t)data[5] << 8))) * 0.03125f + (-273.0f);
    out->engine_intercooler_temperature = (data[6]) * 1.0f + (-40.0f);
    out->engine_intercooler_thermostat_opening = (data[7]) * 0.4f + (0.0f);
}

void decode_eflp1(const uint8_t* data, eflp1_t* out) {
    if (data == NULL || out == NULL) return;

    out->engine_oil_pressure = (data[3]) * 4.0f + (0.0f);
    out->engine_coolant_pressure = (data[4]) * 2.0f + (0.0f);
    out->engine_fuel_delivery_pressure = (data[1]) * 4.0f + (0.0f);
}

void decode_ccvs(const uint8_t* data, ccvs_t* out) {
    if (data == NULL || out == NULL) return;

    out->parking_brake_switch = ((data[0] >> 2) & 0x03);
    out->two_speed_axle_switch = ((data[0] >> 0) & 0x03);
    out->wheel_based_vehicle_speed = (((uint16_t)data[1] | ((uint16_t)data[2] << 8))) * 0.00390625f + (0.0f);
    out->cruise_control_active = ((data[3] >> 0) & 0x03);
    out->cruise_control_enable_switch = ((data[3] >> 2) & 0x03);
    out->brake_switch = ((data[3] >> 4) & 0x03);
    out->clutch_switch = ((data[3] >> 6) & 0x03);
    out->pto_state = ((data[4] >> 0) & 0x1F);
    out->cruise_control_set_speed = data[5];
    out->pto_set_speed = data[6];
}

void decode_lfe(const uint8_t* data, lfe_t* out) {
    if (data == NULL || out == NULL) return;

    out->engine_fuel_rate = (((uint16_t)data[0] | ((uint16_t)data[1] << 8))) * 0.05f + (0.0f);
    out->instantaneous_fuel_economy = (((uint16_t)data[2] | ((uint16_t)data[3] << 8))) * 0.001953125f + (0.0f);
    out->average_fuel_economy = (((uint16_t)data[4] | ((uint16_t)data[5] << 8))) * 0.001953125f + (0.0f);
    out->throttle_position = (data[6]) * 0.4f + (0.0f);
}

void decode_amb(const uint8_t* data, amb_t* out) {
    if (data == NULL || out == NULL) return;

    out->barometric_pressure = (data[0]) * 0.5f + (0.0f);
    out->cab_interior_temperature = (((uint16_t)data[1] | ((uint16_t)data[2] << 8))) * 0.03125f + (-273.0f);
    out->ambient_air_temperature = (((uint16_t)data[3] | ((uint16_t)data[4] << 8))) * 0.03125f + (-273.0f);
    out->engine_air_inlet_temperature = (data[5]) * 1.0f + (-40.0f);
    out->road_surface_temperature = (((uint16_t)data[6] | ((uint16_t)data[7] << 8))) * 0.03125f + (-273.0f);
}

void decode_ic1(const uint8_t* data, ic1_t* out) {
    if (data == NULL || out == NULL) return;

    out->particulate_trap_inlet_pressure = (data[0]) * 0.5f + (0.0f);
    out->boost_pressure = (data[1]) * 2.0f + (0.0f);
    out->engine_intake_manifold_temp = (data[2]) * 1.0f + (-40.0f);
    out->air_inlet_pressure = (data[3]) * 2.0f + (0.0f);
    out->air_filter_differential_pressure = (data[4]) * 0.05f + (0.0f);
    out->exhaust_gas_temperature = (((uint16_t)data[5] | ((uint16_t)data[6] << 8))) * 0.03125f + (-273.0f);
    out->coolant_filter_diff_pressure = (data[7]) * 0.5f + (0.0f);
}

void decode_vep1(const uint8_t* data, vep1_t* out) {
    if (data == NULL || out == NULL) return;

    out->net_battery_current = (((uint16_t)data[0] | ((uint16_t)data[1] << 8))) * 1.0f + (-125.0f);
    out->alternator_current = ((uint16_t)data[2] | ((uint16_t)data[3] << 8));
    out->charging_system_potential = (((uint16_t)data[4] | ((uint16_t)data[5] << 8))) * 0.05f + (0.0f);
    out->battery_potential = (((uint16_t)data[6] | ((uint16_t)data[7] << 8))) * 0.05f + (0.0f);
}

void decode_trf1(const uint8_t* data, trf1_t* out) {
    if (data == NULL || out == NULL) return;

    out->trans_clutch_pressure = (data[0]) * 16.0f + (0.0f);
    out->trans_oil_level1 = (data[1]) * 0.4f + (0.0f);
    out->trans_oil_filter_differential_pressure = (data[2]) * 2.0f + (0.0f);
    out->trans_oil_pressure = (data[3]) * 16.0f + (0.0f);
    out->trans_oil_temperature1 = (((uint16_t)data[4] | ((uint16_t)data[5] << 8))) * 0.03125f + (-273.0f);
    out->trans_oil_level_high_low = (data[6]) * 0.4f + (-50.0f);
    out->trans_oil_level_countdown_timer = data[7];
}

void decode_dd(const uint8_t* data, dd_t* out) {
    if (data == NULL || out == NULL) return;

    out->washer_fluid_level = (data[0]) * 0.4f + (0.0f);
    out->fuel_level1 = (data[1]) * 0.4f + (0.0f);
    out->fuel_filter_differential_pressure = (data[2]) * 2.0f + (0.0f);
    out->engine_oil_filter_differential_pressure = (data[3]) * 0.5f + (0.0f);
    out->cargo_ambient_temperature = (((uint16_t)data[4] | ((uint16_t)data[5] << 8))) * 0.03125f + (-273.0f);
    out->fuel_level2 = (data[6]) * 0.4f + (0.0f);
}
