/**
 * @file j1939_dbc_generated.h
 * @brief Auto-generated J1939 signal definitions from DBC file
 * 
 * DO NOT EDIT - Generated by dbc_parser.py
 */

#ifndef J1939_DBC_GENERATED_H
#define J1939_DBC_GENERATED_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/*===========================================================================*/
/*                        PGN DEFINITIONS                                  */
/*===========================================================================*/

#define PGN_REQUEST              0xEA00  // 59904 - PGN Request Message
#define PGN_ETC1                 0xF002  // 61442 - Electronic Transmission Controller 1 - Shaft speeds and clutch
#define PGN_EEC2                 0xF003  // 61443 - Electronic Engine Controller 2 - Secondary engine control parameters
#define PGN_EEC1                 0xF004  // 61444 - Electronic Engine Controller 1 - Primary engine control parameters
#define PGN_ETC2                 0xF005  // 61445 - Electronic Transmission Controller 2 - Gear selection
#define PGN_VD                   0xFEC1  // 65217 - Vehicle Distance - Odometer and trip distance
#define PGN_DM1                  0xFECA  // 65226 - DM1 Active Diagnostic Trouble Codes
#define PGN_HOURS                0xFEE5  // 65253 - Engine Hours, Revolutions - Engine total runtime
#define PGN_ET1                  0xFEEE  // 65262 - Engine Temperature 1 - Engine temperature readings
#define PGN_EFLP1                0xFEEF  // 65263 - Engine Fluid Level/Pressure 1 - Oil/coolant/fuel pressures
#define PGN_CCVS                 0xFEF1  // 65265 - Cruise Control/Vehicle Speed - Speed and cruise control status
#define PGN_LFE                  0xFEF2  // 65266 - Liquid Fuel Economy - Fuel consumption rates
#define PGN_AMB                  0xFEF5  // 65269 - Ambient Conditions - Environmental temperatures/pressures
#define PGN_IC1                  0xFEF6  // 65270 - Inlet/Exhaust Conditions 1 - Turbo and intake parameters
#define PGN_VEP1                 0xFEF7  // 65271 - Vehicle Electrical Power 1 - Battery and charging info
#define PGN_TRF1                 0xFEF8  // 65272 - Transmission Fluids 1 - Transmission oil parameters
#define PGN_DD                   0xFEFC  // 65276 - Dash Display - Fuel level and filter status

/*===========================================================================*/
/*                        MESSAGE CYCLE TIMES (ms)                        */
/*===========================================================================*/

#define ETC1_CYCLE_MS          10
#define EEC2_CYCLE_MS          50
#define EEC1_CYCLE_MS          10
#define ETC2_CYCLE_MS          100
#define VD_CYCLE_MS          1000
#define HOURS_CYCLE_MS          1000
#define ET1_CYCLE_MS          1000
#define EFLP1_CYCLE_MS          500
#define CCVS_CYCLE_MS          100
#define LFE_CYCLE_MS          100
#define AMB_CYCLE_MS          1000
#define IC1_CYCLE_MS          500
#define VEP1_CYCLE_MS          1000
#define TRF1_CYCLE_MS          1000
#define DD_CYCLE_MS          1000

/*===========================================================================*/
/*                        SIGNAL STRUCTURES                               */
/*===========================================================================*/

/** REQUEST - PGN 59904 (0xEA00) */
/* PGN Request Message */
typedef struct {
    uint32_t   pgn_requested;
} request_t;

/** ETC1 - PGN 61442 (0xF002) */
/* Electronic Transmission Controller 1 - Shaft speeds and clutch */
typedef struct {
    float      input_shaft_speed; // rpm
    float      output_shaft_speed; // rpm
    float      percent_clutch_slip; // %
    uint8_t    prog_shift_disable;
    uint8_t    eng_momentary_overspeed_enable;
    uint8_t    eng_derating_enable;
    uint8_t    source_address_of_torque_limiting;
} etc1_t;

/** EEC2 - PGN 61443 (0xF003) */
/* Electronic Engine Controller 2 - Secondary engine control parameters */
typedef struct {
    float      accel_pedal_pos1; // %
    float      accel_pedal_pos2; // %
    uint8_t    eng_percent_load_at_current_speed; // %
    float      remote_accel_pedal_position; // %
    float      actual_max_available_engine_percent_torque; // %
} eec2_t;

/** EEC1 - PGN 61444 (0xF004) */
/* Electronic Engine Controller 1 - Primary engine control parameters */
typedef struct {
    uint8_t    eng_torque_mode;
    float      actual_eng_percent_torque; // %
    float      drivers_demand_eng_percent_torque; // %
    float      engine_speed; // rpm
    uint8_t    source_address_of_controlling_device;
    uint8_t    eng_starter_mode;
} eec1_t;

/** ETC2 - PGN 61445 (0xF005) */
/* Electronic Transmission Controller 2 - Gear selection */
typedef struct {
    float      selected_gear;
    float      actual_gear_ratio;
    float      current_gear;
    uint16_t   trans_requested_range;
    uint16_t   trans_current_range;
} etc2_t;

/** VD - PGN 65217 (0xFEC1) */
/* Vehicle Distance - Odometer and trip distance */
typedef struct {
    float      total_vehicle_distance; // km
    float      trip_distance; // km
} vd_t;

/** DM1 - PGN 65226 (0xFECA) */
/* DM1 Active Diagnostic Trouble Codes */
typedef struct {
    uint8_t    protect_lamp;
    uint8_t    amber_warning_lamp;
    uint8_t    red_stop_lamp;
    uint8_t    malfunction_indicator_lamp;
    uint8_t    flash_protect_lamp;
    uint8_t    flash_amber_warning_lamp;
    uint8_t    flash_red_stop_lamp;
    uint8_t    flash_malfunction_indicator_lamp;
    uint32_t   spn;
    uint8_t    fmi;
    uint8_t    cm;
    uint8_t    occurrence_count;
} dm1_t;

/** HOURS - PGN 65253 (0xFEE5) */
/* Engine Hours, Revolutions - Engine total runtime */
typedef struct {
    float      eng_total_hours_of_operation; // h
    float      eng_total_revolutions; // r
} hours_t;

/** ET1 - PGN 65262 (0xFEEE) */
/* Engine Temperature 1 - Engine temperature readings */
typedef struct {
    float      engine_coolant_temperature; // degC
    float      fuel_temperature1; // degC
    float      engine_oil_temperature1; // degC
    float      turbo_oil_temperature; // degC
    float      engine_intercooler_temperature; // degC
    float      engine_intercooler_thermostat_opening; // %
} et1_t;

/** EFLP1 - PGN 65263 (0xFEEF) */
/* Engine Fluid Level/Pressure 1 - Oil/coolant/fuel pressures */
typedef struct {
    float      engine_oil_pressure; // kPa
    float      engine_coolant_pressure; // kPa
    float      engine_fuel_delivery_pressure; // kPa
} eflp1_t;

/** CCVS - PGN 65265 (0xFEF1) */
/* Cruise Control/Vehicle Speed - Speed and cruise control status */
typedef struct {
    uint8_t    parking_brake_switch;
    uint8_t    two_speed_axle_switch;
    float      wheel_based_vehicle_speed; // km/h
    uint8_t    cruise_control_active;
    uint8_t    cruise_control_enable_switch;
    uint8_t    brake_switch;
    uint8_t    clutch_switch;
    uint8_t    pto_state;
    uint8_t    cruise_control_set_speed; // km/h
    uint8_t    pto_set_speed; // rpm
} ccvs_t;

/** LFE - PGN 65266 (0xFEF2) */
/* Liquid Fuel Economy - Fuel consumption rates */
typedef struct {
    float      engine_fuel_rate; // L/h
    float      instantaneous_fuel_economy; // km/L
    float      average_fuel_economy; // km/L
    float      throttle_position; // %
} lfe_t;

/** AMB - PGN 65269 (0xFEF5) */
/* Ambient Conditions - Environmental temperatures/pressures */
typedef struct {
    float      barometric_pressure; // kPa
    float      cab_interior_temperature; // degC
    float      ambient_air_temperature; // degC
    float      engine_air_inlet_temperature; // degC
    float      road_surface_temperature; // degC
} amb_t;

/** IC1 - PGN 65270 (0xFEF6) */
/* Inlet/Exhaust Conditions 1 - Turbo and intake parameters */
typedef struct {
    float      particulate_trap_inlet_pressure; // kPa
    float      boost_pressure; // kPa
    float      engine_intake_manifold_temp; // degC
    float      air_inlet_pressure; // kPa
    float      air_filter_differential_pressure; // kPa
    float      exhaust_gas_temperature; // degC
    float      coolant_filter_diff_pressure; // kPa
} ic1_t;

/** VEP1 - PGN 65271 (0xFEF7) */
/* Vehicle Electrical Power 1 - Battery and charging info */
typedef struct {
    float      net_battery_current; // A
    uint16_t   alternator_current; // A
    float      charging_system_potential; // V
    float      battery_potential; // V
} vep1_t;

/** TRF1 - PGN 65272 (0xFEF8) */
/* Transmission Fluids 1 - Transmission oil parameters */
typedef struct {
    float      trans_clutch_pressure; // kPa
    float      trans_oil_level1; // %
    float      trans_oil_filter_differential_pressure; // kPa
    float      trans_oil_pressure; // kPa
    float      trans_oil_temperature1; // degC
    float      trans_oil_level_high_low; // %
    uint8_t    trans_oil_level_countdown_timer; // s
} trf1_t;

/** DD - PGN 65276 (0xFEFC) */
/* Dash Display - Fuel level and filter status */
typedef struct {
    float      washer_fluid_level; // %
    float      fuel_level1; // %
    float      fuel_filter_differential_pressure; // kPa
    float      engine_oil_filter_differential_pressure; // kPa
    float      cargo_ambient_temperature; // degC
    float      fuel_level2; // %
} dd_t;

/*===========================================================================*/
/*                        DECODER FUNCTIONS                               */
/*===========================================================================*/

/** Decode REQUEST message (PGN 59904) */
void decode_request(const uint8_t* data, request_t* out);

/** Decode ETC1 message (PGN 61442) */
void decode_etc1(const uint8_t* data, etc1_t* out);

/** Decode EEC2 message (PGN 61443) */
void decode_eec2(const uint8_t* data, eec2_t* out);

/** Decode EEC1 message (PGN 61444) */
void decode_eec1(const uint8_t* data, eec1_t* out);

/** Decode ETC2 message (PGN 61445) */
void decode_etc2(const uint8_t* data, etc2_t* out);

/** Decode VD message (PGN 65217) */
void decode_vd(const uint8_t* data, vd_t* out);

/** Decode DM1 message (PGN 65226) */
void decode_dm1(const uint8_t* data, dm1_t* out);

/** Decode HOURS message (PGN 65253) */
void decode_hours(const uint8_t* data, hours_t* out);

/** Decode ET1 message (PGN 65262) */
void decode_et1(const uint8_t* data, et1_t* out);

/** Decode EFLP1 message (PGN 65263) */
void decode_eflp1(const uint8_t* data, eflp1_t* out);

/** Decode CCVS message (PGN 65265) */
void decode_ccvs(const uint8_t* data, ccvs_t* out);

/** Decode LFE message (PGN 65266) */
void decode_lfe(const uint8_t* data, lfe_t* out);

/** Decode AMB message (PGN 65269) */
void decode_amb(const uint8_t* data, amb_t* out);

/** Decode IC1 message (PGN 65270) */
void decode_ic1(const uint8_t* data, ic1_t* out);

/** Decode VEP1 message (PGN 65271) */
void decode_vep1(const uint8_t* data, vep1_t* out);

/** Decode TRF1 message (PGN 65272) */
void decode_trf1(const uint8_t* data, trf1_t* out);

/** Decode DD message (PGN 65276) */
void decode_dd(const uint8_t* data, dd_t* out);

/*===========================================================================*/
/*                        SIGNAL EXTRACTION MACROS                        */
/*===========================================================================*/

/* REQUEST.PGNRequested: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 16777215.0]  */

/* ETC1.InputShaftSpeed: No description */
/* Scale: 0.125, Offset: 0.0, Range: [0.0, 8031.875] rpm */
#define GET_ETC1_INPUTSHAFTSPEED(data) ((((uint16_t)data[0] | ((uint16_t)data[1] << 8))) * 0.125f + (0.0f))

/* ETC1.OutputShaftSpeed: No description */
/* Scale: 0.125, Offset: 0.0, Range: [0.0, 8031.875] rpm */
#define GET_ETC1_OUTPUTSHAFTSPEED(data) ((((uint16_t)data[2] | ((uint16_t)data[3] << 8))) * 0.125f + (0.0f))

/* ETC1.PercentClutchSlip: No description */
/* Scale: 0.4, Offset: 0.0, Range: [0.0, 100.0] % */
#define GET_ETC1_PERCENTCLUTCHSLIP(data) (((data[4])) * 0.4f + (0.0f))

/* ETC1.ProgShiftDisable: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_ETC1_PROGSHIFTDISABLE(data) (((data[5] >> 2) & 0x03))

/* ETC1.EngMomentaryOverspeedEnable: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_ETC1_ENGMOMENTARYOVERSPEEDENABLE(data) (((data[5] >> 4) & 0x03))

/* ETC1.EngDeratingEnable: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_ETC1_ENGDERATINGENABLE(data) (((data[5] >> 6) & 0x03))

/* ETC1.SourceAddressOfTorqueLimiting: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 255.0]  */
#define GET_ETC1_SOURCEADDRESSOFTORQUELIMITING(data) ((data[6]))

/* EEC2.AccelPedalPos1: No description */
/* Scale: 0.4, Offset: 0.0, Range: [0.0, 102.0] % */
#define GET_EEC2_ACCELPEDALPOS1(data) (((data[1])) * 0.4f + (0.0f))

/* EEC2.AccelPedalPos2: No description */
/* Scale: 0.4, Offset: 0.0, Range: [0.0, 102.0] % */
#define GET_EEC2_ACCELPEDALPOS2(data) (((data[7])) * 0.4f + (0.0f))

/* EEC2.EngPercentLoadAtCurrentSpeed: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 100.0] % */
#define GET_EEC2_ENGPERCENTLOADATCURRENTSPEED(data) ((data[2]))

/* EEC2.RemoteAccelPedalPosition: No description */
/* Scale: 0.4, Offset: 0.0, Range: [0.0, 102.0] % */
#define GET_EEC2_REMOTEACCELPEDALPOSITION(data) (((data[3])) * 0.4f + (0.0f))

/* EEC2.ActualMaxAvailableEnginePercentTorque: No description */
/* Scale: 0.4, Offset: 0.0, Range: [0.0, 102.0] % */
#define GET_EEC2_ACTUALMAXAVAILABLEENGINEPERCENTTORQUE(data) (((data[5])) * 0.4f + (0.0f))

/* EEC1.EngTorqueMode: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 15.0]  */
#define GET_EEC1_ENGTORQUEMODE(data) (((data[0] >> 0) & 0x0F))

/* EEC1.ActualEngPercentTorque: Current engine torque as percentage of reference torque */
/* Scale: 1.0, Offset: -125.0, Range: [-125.0, 125.0] % */
#define GET_EEC1_ACTUALENGPERCENTTORQUE(data) (((data[2])) * 1.0f + (-125.0f))

/* EEC1.DriversDemandEngPercentTorque: No description */
/* Scale: 1.0, Offset: -125.0, Range: [-125.0, 125.0] % */
#define GET_EEC1_DRIVERSDEMANDENGPERCENTTORQUE(data) (((data[1])) * 1.0f + (-125.0f))

/* EEC1.EngineSpeed: Engine crankshaft speed - 0.125 RPM/bit */
/* Scale: 0.125, Offset: 0.0, Range: [0.0, 8031.875] rpm */
#define GET_EEC1_ENGINESPEED(data) ((((uint16_t)data[3] | ((uint16_t)data[4] << 8))) * 0.125f + (0.0f))

/* EEC1.SourceAddressOfControllingDevice: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 255.0]  */
#define GET_EEC1_SOURCEADDRESSOFCONTROLLINGDEVICE(data) ((data[5]))

/* EEC1.EngStarterMode: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 15.0]  */
#define GET_EEC1_ENGSTARTERMODE(data) (((data[6] >> 0) & 0x0F))

/* ETC2.SelectedGear: No description */
/* Scale: 1.0, Offset: -125.0, Range: [-125.0, 125.0]  */
#define GET_ETC2_SELECTEDGEAR(data) (((data[0])) * 1.0f + (-125.0f))

/* ETC2.ActualGearRatio: No description */
/* Scale: 0.001, Offset: 0.0, Range: [0.0, 64.255]  */
#define GET_ETC2_ACTUALGEARRATIO(data) ((((uint16_t)data[1] | ((uint16_t)data[2] << 8))) * 0.001f + (0.0f))

/* ETC2.CurrentGear: Currently engaged transmission gear */
/* Scale: 1.0, Offset: -125.0, Range: [-125.0, 125.0]  */
#define GET_ETC2_CURRENTGEAR(data) (((data[3])) * 1.0f + (-125.0f))

/* ETC2.TransRequestedRange: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 65535.0]  */
#define GET_ETC2_TRANSREQUESTEDRANGE(data) (((uint16_t)data[4] | ((uint16_t)data[5] << 8)))

/* ETC2.TransCurrentRange: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 65535.0]  */
#define GET_ETC2_TRANSCURRENTRANGE(data) (((uint16_t)data[6] | ((uint16_t)data[7] << 8)))

/* VD.TotalVehicleDistance: No description */
/* Scale: 0.125, Offset: 0.0, Range: [0.0, 536870911.875] km */

/* VD.TripDistance: No description */
/* Scale: 0.125, Offset: 0.0, Range: [0.0, 536870911.875] km */

/* DM1.ProtectLamp: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_DM1_PROTECTLAMP(data) (((data[0] >> 0) & 0x03))

/* DM1.AmberWarningLamp: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_DM1_AMBERWARNINGLAMP(data) (((data[0] >> 2) & 0x03))

/* DM1.RedStopLamp: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_DM1_REDSTOPLAMP(data) (((data[0] >> 4) & 0x03))

/* DM1.MalfunctionIndicatorLamp: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_DM1_MALFUNCTIONINDICATORLAMP(data) (((data[0] >> 6) & 0x03))

/* DM1.FlashProtectLamp: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_DM1_FLASHPROTECTLAMP(data) (((data[1] >> 0) & 0x03))

/* DM1.FlashAmberWarningLamp: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_DM1_FLASHAMBERWARNINGLAMP(data) (((data[1] >> 2) & 0x03))

/* DM1.FlashRedStopLamp: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_DM1_FLASHREDSTOPLAMP(data) (((data[1] >> 4) & 0x03))

/* DM1.FlashMalfunctionIndicatorLamp: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_DM1_FLASHMALFUNCTIONINDICATORLAMP(data) (((data[1] >> 6) & 0x03))

/* DM1.SPN: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 524287.0]  */

/* DM1.FMI: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 31.0]  */
#define GET_DM1_FMI(data) (((data[4] >> 3) & 0x1F))

/* DM1.CM: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 1.0]  */
#define GET_DM1_CM(data) (((data[5] >> 0) & 0x01))

/* DM1.OccurrenceCount: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 127.0]  */
#define GET_DM1_OCCURRENCECOUNT(data) (((data[5] >> 1) & 0x7F))

/* HOURS.EngTotalHoursOfOperation: No description */
/* Scale: 0.05, Offset: 0.0, Range: [0.0, 214748364.75] h */

/* HOURS.EngTotalRevolutions: No description */
/* Scale: 1000.0, Offset: 0.0, Range: [0.0, 4294967295000.0] r */

/* ET1.EngineCoolantTemperature: Temperature of engine coolant fluid */
/* Scale: 1.0, Offset: -40.0, Range: [-40.0, 210.0] degC */
#define GET_ET1_ENGINECOOLANTTEMPERATURE(data) (((data[0])) * 1.0f + (-40.0f))

/* ET1.FuelTemperature1: No description */
/* Scale: 1.0, Offset: -40.0, Range: [-40.0, 210.0] degC */
#define GET_ET1_FUELTEMPERATURE1(data) (((data[1])) * 1.0f + (-40.0f))

/* ET1.EngineOilTemperature1: No description */
/* Scale: 0.03125, Offset: -273.0, Range: [-273.0, 1735.0] degC */
#define GET_ET1_ENGINEOILTEMPERATURE1(data) ((((uint16_t)data[2] | ((uint16_t)data[3] << 8))) * 0.03125f + (-273.0f))

/* ET1.TurboOilTemperature: No description */
/* Scale: 0.03125, Offset: -273.0, Range: [-273.0, 1735.0] degC */
#define GET_ET1_TURBOOILTEMPERATURE(data) ((((uint16_t)data[4] | ((uint16_t)data[5] << 8))) * 0.03125f + (-273.0f))

/* ET1.EngineIntercoolerTemperature: No description */
/* Scale: 1.0, Offset: -40.0, Range: [-40.0, 210.0] degC */
#define GET_ET1_ENGINEINTERCOOLERTEMPERATURE(data) (((data[6])) * 1.0f + (-40.0f))

/* ET1.EngineIntercoolerThermostatOpening: No description */
/* Scale: 0.4, Offset: 0.0, Range: [0.0, 102.0] % */
#define GET_ET1_ENGINEINTERCOOLERTHERMOSTATOPENING(data) (((data[7])) * 0.4f + (0.0f))

/* EFLP1.EngineOilPressure: No description */
/* Scale: 4.0, Offset: 0.0, Range: [0.0, 1000.0] kPa */
#define GET_EFLP1_ENGINEOILPRESSURE(data) (((data[3])) * 4.0f + (0.0f))

/* EFLP1.EngineCoolantPressure: No description */
/* Scale: 2.0, Offset: 0.0, Range: [0.0, 500.0] kPa */
#define GET_EFLP1_ENGINECOOLANTPRESSURE(data) (((data[4])) * 2.0f + (0.0f))

/* EFLP1.EngineFuelDeliveryPressure: No description */
/* Scale: 4.0, Offset: 0.0, Range: [0.0, 1000.0] kPa */
#define GET_EFLP1_ENGINEFUELDELIVERYPRESSURE(data) (((data[1])) * 4.0f + (0.0f))

/* CCVS.ParkingBrakeSwitch: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_CCVS_PARKINGBRAKESWITCH(data) (((data[0] >> 2) & 0x03))

/* CCVS.TwoSpeedAxleSwitch: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_CCVS_TWOSPEEDAXLESWITCH(data) (((data[0] >> 0) & 0x03))

/* CCVS.WheelBasedVehicleSpeed: Vehicle speed from wheel speed sensors */
/* Scale: 0.00390625, Offset: 0.0, Range: [0.0, 250.996] km/h */
#define GET_CCVS_WHEELBASEDVEHICLESPEED(data) ((((uint16_t)data[1] | ((uint16_t)data[2] << 8))) * 0.00390625f + (0.0f))

/* CCVS.CruiseControlActive: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_CCVS_CRUISECONTROLACTIVE(data) (((data[3] >> 0) & 0x03))

/* CCVS.CruiseControlEnableSwitch: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_CCVS_CRUISECONTROLENABLESWITCH(data) (((data[3] >> 2) & 0x03))

/* CCVS.BrakeSwitch: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_CCVS_BRAKESWITCH(data) (((data[3] >> 4) & 0x03))

/* CCVS.ClutchSwitch: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 3.0]  */
#define GET_CCVS_CLUTCHSWITCH(data) (((data[3] >> 6) & 0x03))

/* CCVS.PTOState: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 31.0]  */
#define GET_CCVS_PTOSTATE(data) (((data[4] >> 0) & 0x1F))

/* CCVS.CruiseControlSetSpeed: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 250.0] km/h */
#define GET_CCVS_CRUISECONTROLSETSPEED(data) ((data[5]))

/* CCVS.PTOSetSpeed: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 255.0] rpm */
#define GET_CCVS_PTOSETSPEED(data) ((data[6]))

/* LFE.EngineFuelRate: No description */
/* Scale: 0.05, Offset: 0.0, Range: [0.0, 3212.75] L/h */
#define GET_LFE_ENGINEFUELRATE(data) ((((uint16_t)data[0] | ((uint16_t)data[1] << 8))) * 0.05f + (0.0f))

/* LFE.InstantaneousFuelEconomy: No description */
/* Scale: 0.001953125, Offset: 0.0, Range: [0.0, 125.5] km/L */
#define GET_LFE_INSTANTANEOUSFUELECONOMY(data) ((((uint16_t)data[2] | ((uint16_t)data[3] << 8))) * 0.001953125f + (0.0f))

/* LFE.AverageFuelEconomy: No description */
/* Scale: 0.001953125, Offset: 0.0, Range: [0.0, 125.5] km/L */
#define GET_LFE_AVERAGEFUELECONOMY(data) ((((uint16_t)data[4] | ((uint16_t)data[5] << 8))) * 0.001953125f + (0.0f))

/* LFE.ThrottlePosition: No description */
/* Scale: 0.4, Offset: 0.0, Range: [0.0, 100.0] % */
#define GET_LFE_THROTTLEPOSITION(data) (((data[6])) * 0.4f + (0.0f))

/* AMB.BarometricPressure: No description */
/* Scale: 0.5, Offset: 0.0, Range: [0.0, 125.0] kPa */
#define GET_AMB_BAROMETRICPRESSURE(data) (((data[0])) * 0.5f + (0.0f))

/* AMB.CabInteriorTemperature: No description */
/* Scale: 0.03125, Offset: -273.0, Range: [-273.0, 1735.0] degC */
#define GET_AMB_CABINTERIORTEMPERATURE(data) ((((uint16_t)data[1] | ((uint16_t)data[2] << 8))) * 0.03125f + (-273.0f))

/* AMB.AmbientAirTemperature: No description */
/* Scale: 0.03125, Offset: -273.0, Range: [-273.0, 1735.0] degC */
#define GET_AMB_AMBIENTAIRTEMPERATURE(data) ((((uint16_t)data[3] | ((uint16_t)data[4] << 8))) * 0.03125f + (-273.0f))

/* AMB.EngineAirInletTemperature: No description */
/* Scale: 1.0, Offset: -40.0, Range: [-40.0, 210.0] degC */
#define GET_AMB_ENGINEAIRINLETTEMPERATURE(data) (((data[5])) * 1.0f + (-40.0f))

/* AMB.RoadSurfaceTemperature: No description */
/* Scale: 0.03125, Offset: -273.0, Range: [-273.0, 1735.0] degC */
#define GET_AMB_ROADSURFACETEMPERATURE(data) ((((uint16_t)data[6] | ((uint16_t)data[7] << 8))) * 0.03125f + (-273.0f))

/* IC1.ParticulateTrapInletPressure: No description */
/* Scale: 0.5, Offset: 0.0, Range: [0.0, 125.0] kPa */
#define GET_IC1_PARTICULATETRAPINLETPRESSURE(data) (((data[0])) * 0.5f + (0.0f))

/* IC1.BoostPressure: Turbocharger boost pressure */
/* Scale: 2.0, Offset: 0.0, Range: [0.0, 500.0] kPa */
#define GET_IC1_BOOSTPRESSURE(data) (((data[1])) * 2.0f + (0.0f))

/* IC1.EngineIntakeManifoldTemp: No description */
/* Scale: 1.0, Offset: -40.0, Range: [-40.0, 210.0] degC */
#define GET_IC1_ENGINEINTAKEMANIFOLDTEMP(data) (((data[2])) * 1.0f + (-40.0f))

/* IC1.AirInletPressure: No description */
/* Scale: 2.0, Offset: 0.0, Range: [0.0, 500.0] kPa */
#define GET_IC1_AIRINLETPRESSURE(data) (((data[3])) * 2.0f + (0.0f))

/* IC1.AirFilterDifferentialPressure: No description */
/* Scale: 0.05, Offset: 0.0, Range: [0.0, 12.5] kPa */
#define GET_IC1_AIRFILTERDIFFERENTIALPRESSURE(data) (((data[4])) * 0.05f + (0.0f))

/* IC1.ExhaustGasTemperature: No description */
/* Scale: 0.03125, Offset: -273.0, Range: [-273.0, 1735.0] degC */
#define GET_IC1_EXHAUSTGASTEMPERATURE(data) ((((uint16_t)data[5] | ((uint16_t)data[6] << 8))) * 0.03125f + (-273.0f))

/* IC1.CoolantFilterDiffPressure: No description */
/* Scale: 0.5, Offset: 0.0, Range: [0.0, 125.0] kPa */
#define GET_IC1_COOLANTFILTERDIFFPRESSURE(data) (((data[7])) * 0.5f + (0.0f))

/* VEP1.NetBatteryCurrent: No description */
/* Scale: 1.0, Offset: -125.0, Range: [-125.0, 125.0] A */
#define GET_VEP1_NETBATTERYCURRENT(data) ((((uint16_t)data[0] | ((uint16_t)data[1] << 8))) * 1.0f + (-125.0f))

/* VEP1.AlternatorCurrent: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 250.0] A */
#define GET_VEP1_ALTERNATORCURRENT(data) (((uint16_t)data[2] | ((uint16_t)data[3] << 8)))

/* VEP1.ChargingSystemPotential: No description */
/* Scale: 0.05, Offset: 0.0, Range: [0.0, 3212.75] V */
#define GET_VEP1_CHARGINGSYSTEMPOTENTIAL(data) ((((uint16_t)data[4] | ((uint16_t)data[5] << 8))) * 0.05f + (0.0f))

/* VEP1.BatteryPotential: No description */
/* Scale: 0.05, Offset: 0.0, Range: [0.0, 3212.75] V */
#define GET_VEP1_BATTERYPOTENTIAL(data) ((((uint16_t)data[6] | ((uint16_t)data[7] << 8))) * 0.05f + (0.0f))

/* TRF1.TransClutchPressure: No description */
/* Scale: 16.0, Offset: 0.0, Range: [0.0, 4000.0] kPa */
#define GET_TRF1_TRANSCLUTCHPRESSURE(data) (((data[0])) * 16.0f + (0.0f))

/* TRF1.TransOilLevel1: No description */
/* Scale: 0.4, Offset: 0.0, Range: [0.0, 100.0] % */
#define GET_TRF1_TRANSOILLEVEL1(data) (((data[1])) * 0.4f + (0.0f))

/* TRF1.TransOilFilterDifferentialPressure: No description */
/* Scale: 2.0, Offset: 0.0, Range: [0.0, 500.0] kPa */
#define GET_TRF1_TRANSOILFILTERDIFFERENTIALPRESSURE(data) (((data[2])) * 2.0f + (0.0f))

/* TRF1.TransOilPressure: No description */
/* Scale: 16.0, Offset: 0.0, Range: [0.0, 4000.0] kPa */
#define GET_TRF1_TRANSOILPRESSURE(data) (((data[3])) * 16.0f + (0.0f))

/* TRF1.TransOilTemperature1: No description */
/* Scale: 0.03125, Offset: -273.0, Range: [-273.0, 1735.0] degC */
#define GET_TRF1_TRANSOILTEMPERATURE1(data) ((((uint16_t)data[4] | ((uint16_t)data[5] << 8))) * 0.03125f + (-273.0f))

/* TRF1.TransOilLevelHighLow: No description */
/* Scale: 0.4, Offset: -50.0, Range: [-50.0, 51.2] % */
#define GET_TRF1_TRANSOILLEVELHIGHLOW(data) (((data[6])) * 0.4f + (-50.0f))

/* TRF1.TransOilLevelCountdownTimer: No description */
/* Scale: 1.0, Offset: 0.0, Range: [0.0, 250.0] s */
#define GET_TRF1_TRANSOILLEVELCOUNTDOWNTIMER(data) ((data[7]))

/* DD.WasherFluidLevel: No description */
/* Scale: 0.4, Offset: 0.0, Range: [0.0, 100.0] % */
#define GET_DD_WASHERFLUIDLEVEL(data) (((data[0])) * 0.4f + (0.0f))

/* DD.FuelLevel1: Primary fuel tank level percentage */
/* Scale: 0.4, Offset: 0.0, Range: [0.0, 100.0] % */
#define GET_DD_FUELLEVEL1(data) (((data[1])) * 0.4f + (0.0f))

/* DD.FuelFilterDifferentialPressure: No description */
/* Scale: 2.0, Offset: 0.0, Range: [0.0, 500.0] kPa */
#define GET_DD_FUELFILTERDIFFERENTIALPRESSURE(data) (((data[2])) * 2.0f + (0.0f))

/* DD.EngineOilFilterDifferentialPressure: No description */
/* Scale: 0.5, Offset: 0.0, Range: [0.0, 125.0] kPa */
#define GET_DD_ENGINEOILFILTERDIFFERENTIALPRESSURE(data) (((data[3])) * 0.5f + (0.0f))

/* DD.CargoAmbientTemperature: No description */
/* Scale: 0.03125, Offset: -273.0, Range: [-273.0, 1735.0] degC */
#define GET_DD_CARGOAMBIENTTEMPERATURE(data) ((((uint16_t)data[4] | ((uint16_t)data[5] << 8))) * 0.03125f + (-273.0f))

/* DD.FuelLevel2: No description */
/* Scale: 0.4, Offset: 0.0, Range: [0.0, 100.0] % */
#define GET_DD_FUELLEVEL2(data) (((data[6])) * 0.4f + (0.0f))

/*===========================================================================*/
/*                        VALIDITY CHECKS                                 */
/*===========================================================================*/

/* J1939 'Not Available' values */
#define J1939_NA_8BIT       0xFF
#define J1939_NA_16BIT      0xFFFF
#define J1939_NA_32BIT      0xFFFFFFFF

#define IS_VALID_8(val)     ((val) != J1939_NA_8BIT)
#define IS_VALID_16(val)    ((val) != J1939_NA_16BIT)
#define IS_VALID_32(val)    ((val) != J1939_NA_32BIT)

#ifdef __cplusplus
}
#endif

#endif // J1939_DBC_GENERATED_H
